_authenticated_path: proxy.path is bytes
We must decode proxy.path before calling split(), or we get a TypeError
on Python 3.

  TypeError: a bytes-like object is required, not 'str'

... and then re-encode our return value so we can re-assign it with the
right encoding to proxy.path.